services:
  - type: web
    name: blinkeach-production
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    domains:
      - blinkeach.in
      - www.blinkeach.in
      - blinkeach.com
      - www.blinkeach.com
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blinkeach-production-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: DELHIVERY_API_KEY
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DOMAIN_URL
        value: https://blinkeach.in
      - key: ALLOWED_ORIGINS
        value: https://blinkeach.in,https://www.blinkeach.in,https://blinkeach.com,https://www.blinkeach.com

databases:
  - name: blinkeach-production-db
    databaseName: blinkeach_prod
    user: blinkeach_prod_user
    plan: starter